import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";

export default function Video() {
  const router = useRouter();
  const { id } = router.query;

  return (
    <div>
      <Head>
        <title>Video Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Video id:{id}</div>
    </div>
  );
}
