import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import LiteYouTubeEmbed from "react-lite-youtube-embed";
import "react-lite-youtube-embed/dist/LiteYouTubeEmbed.css";
import styles from "../styles/video.module.css";

export default function Video() {
  const router = useRouter();
  const { id } = router.query;

  return (
    <div>
      <Head>
        <title>Video Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.video}>
        <LiteYouTubeEmbed id={id} />
      </div>
    </div>
  );
}
